name: super ci of the dead

on:
 push:
  branches: 
    - main

jobs:
  initialisation:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: liste des fichiers
        run: ls
