name: super ci of the dead

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

  install:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  audit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Node audit
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          only: prod
          level: moderate
          project-path: .

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: EsLint
        run: npx eslint .